'use client'
// import type { Metadata } from "next";
import './globals.css'

import { Inter } from 'next/font/google'

import { AuthProvider } from '@/context/AuthContext'
import NextAuthSessionProvider from '@/providers/sessionProvider'

const inter = Inter({ subsets: ['latin'] })

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <AuthProvider>
        <body className={inter.className}>
          <NextAuthSessionProvider>{children}</NextAuthSessionProvider>
        </body>
      </AuthProvider>
    </html>
  )
}
